<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	File: qa-include/qa-lang-main.php
	Description: Language phrases commonly used throughout Q2A


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
	korea translation made by minwook shin
	https://github.com/minwook-shin
*/

	return array(
		'1_answer' => '1개의 답변',
		'1_comment' => '1개의 댓글',
		'1_day' => '1일',
		'1_disliked' => '1명이 싫어함',
		'1_flag' => '1명이 신고함',
		'1_hour' => '1시간',
		'1_liked' => '1명이 좋아함',
		'1_minute' => '1분',
		'1_month' => '1달',
		'1_point' => '1포인트',
		'1_question' => '1개의 질문',
		'1_second' => '1초',
		'1_tag' => '1개의 태그',
		'1_user' => '1명의 유저',
		'1_view' => '1명이 봄',
		'1_vote' => '1추천',
		'1_week' => '1주',
		'1_year' => '1년',
		'add_category_x_favorites' => '내 즐겨찾기로 ^카테고리 추가',
		'add_favorites' => '내 즐겨찾기를 추가',
		'add_tag_x_favorites' => '내 즐겨찾기의 ^태그 추가',
		'all_categories' => '모든 카테고리',
		'anonymous' => '익명',
		'answer_edited' => '답변이 수정됨',
		'answer_reshown' => '답변 다시 보기',
		'answer_selected' => '답변 선택',
		'answered_qs_in_x' => '^에서 가장 많이 답변된 질문',
		'answered_qs_title' => '가장 많이 답변된 질문',
		'answered' => '답변함',
		'asked_related_q' => '문의된 관련 질문',
		'asked' => '물어봄',
		'by_x' => '^님이',
		'cancel_button' => '취소',
		'closed' => '닫힘',
		'comment_edited' => '댓글이 수정됨',
		'comment_moved' => '댓글이 이동됨',
		'comment_reshown' => '댓글 다시 보기',
		'commented' => '댓글담',
		'date_day_min_digits' => 1, // 1 or 2
		'date_format_other_years' => '^year년 ^month ^day일',
		'date_format_this_year' => '^month ^day일',
		'date_month_1' => '1월',
		'date_month_2' => '2월',
		'date_month_3' => '3월',
		'date_month_4' => '4월',
		'date_month_5' => '5월',
		'date_month_6' => '6월',
		'date_month_7' => '7월',
		'date_month_8' => '8월',
		'date_month_9' => '9월',
		'date_month_10' => '10월',
		'date_month_11' => '11월',
		'date_month_12' => '12월',
		'date_year_digits' => 4, // 2 or 4
		'edited' => '수정함',
		'email_error' => '이메일을 보내는 중 오류가 발생했습니다.',
		'field_required' => '이 칸은 비워둘 수 없습니다.',
		'file_upload_limit_exceeded' => '파일의 크기가 서버 \'의 한계를 초과했습니다.',
		'general_error' => '서버 오류가 발생했습니다 - 다시 시도해 주십시오.',
		'hidden' => '숨김',
		'highest_users' => '높은 순위 유저',
		'hot_qs_in_x' => '인기있는 질문의 ^',
		'hot_qs_title' => '인기있는 질문',
		'image_not_read' => '이미지를 읽을 수 없습니다. 다음 중 하나를 업로드 하십시오. ^',
		'image_too_big_x_pc' => '이 이미지는 너무 큽니다. ^ % 사이즈 조정후 다시 시도하십시오 .',
		'in_category_x' => '^의',
		'ip_address_x' => 'IP 주소 ^',
		'logged_in_x' => '안녕하세요, ^님.',
		'max_length_x' => '최대 길이는 ^자입니다.',
		'me' => '나',
		'meta_order' => '^where^who^when^what', // you can reorder but DO NOT translate! e.g. <answered> <15 hours ago> <in Problems> <by me (500 points)>
		'min_length_x' => '내용이 너무 짧습니다. 적어도 ^ 글자를 적어야 합니다.',
		'max_upload_size_x' => '최대 업로드 사이즈는 ^입니다.',
		'moved' => '이동함',
		'nav_activity' => '모든 활동',
		'nav_admin' => '관리자',
		'nav_ask' => '질문하기',
		'nav_categories' => '카테고리',
		'nav_feedback' => '피드백 보내기',
		'nav_home' => '홈',
		'nav_hot' => '인기짱!',
		'nav_login' => '로그인',
		'nav_logout' => '로그아웃',
		'nav_most_answers' => '답을 많이 받음',
		'nav_most_recent' => '최근',
		'nav_most_views' => '가장 많이 봄',
		'nav_most_votes' => '많은 추천',
		'nav_no_answer' => '답변 없음',
		'nav_no_selected_answer' => '채택된 답변 없음',
		'nav_no_upvoted_answer' => '좋아요 표시된 답변 없음',
		'nav_qa' => '질문과 답변',
		'nav_qs' => '질문',
		'nav_register' => '가입',
		'nav_tags' => '태그',
		'nav_unanswered' => '응답해줘',
		'nav_updates' => '나의 업데이트',
		'nav_users' => '유저',
		'no_active_users' => '활성화 유저를 찾을 수 없음',
		'no_answers_found' => '답변을 찾을 수 없음',
		'no_answers_in_x' => '^ 답변 없음',
		'no_categories_found' => '카테고리를 찾을 수 없음',
		'no_category' => '카테고리 없음',
		'no_comments_found' => '댓글을 찾을 수 없음',
		'no_comments_in_x' => '^ 댓글 없음',
		'no_questions_found' => '질문을 찾을 수 없음',
		'no_questions_in_x' => '^ 질문 없음',
		'no_related_qs_title' => '관련 질문 없음',
		'no_results_for_x' => '^의 관련 질문 없음',
		'no_tags_found' => '태그를 찾을 수 없음',
		'no_una_questions_found' => '답변없는 질문을 찾을 수 없음',
		'no_una_questions_in_x' => '^ 답변없는 질문을 찾을 수 없음',
		'no_unselected_qs_found' => '답변이 선택되지 않은 질문을 찾을 수 없음',
		'no_unupvoteda_qs_found' => '좋아요 투표가 없는 답변을 찾을 수 없음',
		'page_label' => '페이지:',
		'page_next' => '다음',
		'page_not_found' => '페이지를 찾을 수 없음',
		'page_prev' => '이전',
		'popular_tags' => '가장 인기 있는 태그',
		'questions_tagged_x' => '최근 질문으로 태그된 ^',
		'recategorized' => '재분류',
		'recent_activity_in_x' => '최근 활동 ^',
		'recent_activity_title' => '최근활동',
		'recent_as_in_x' => '최근 질문에 대한 답변 ^',
		'recent_as_title' => '최근 질문에 대한 답변',
		'recent_cs_in_x' => '최근 댓글의 질문 ^',
		'recent_cs_title' => '최근 댓글의 질문',
		'recent_qs_as_in_x' => '최근 질문과 답변 ^',
		'recent_qs_as_title' => '최근 질문과 답변',
		'recent_qs_in_x' => '최근 질문 ^',
		'recent_qs_title' => '최근 질문',
		'related_qs_title' => '관련 질문',
		'remove_favorites' => '내 즐겨찾기로부터 삭제',
		'remove_x_favorites' => '내 즐겨찾기로 부터 ^ 삭제',
		'reopened' => '다시 오픈',
		'reshown' => '다시 보기',
		'results_for_x' => '^의 검색 결과',
		'retagged' => '재 태그',
		'save_button' => '변경사항 저장',
		'search_button' => '찾기',
		'search_explanation' => '검색 창에 텍스트를 입력하고 다시 시도하십시오.',
		'search_title' => '검색 결과',
		'selected' => '선택함',
		'send_button' => '보내기',
		'since_x' => '생성 년도 ^',
		'suggest_ask' => '^1질문하기^2로 도움을 받아보십시오.',
		'suggest_category_qs' => '더 보려면, ^1이 카테고리의 질문^2을 모두 클릭하십시오.',
		'suggest_qs_tags' => '더 보려면, ^1질문의 전체 목록^2 또는 ^3인기 태그^4를 클릭하십시오.',
		'suggest_qs' => '더 보려면,^1질문의 전체 목록^2을 클릭하십시오.',
		'to_x' => '^에',
		'unanswered_qs_in_x' => '답변이 없는 질문 ^',
		'unanswered_qs_title' => '답변이 없는 최근 질문',
		'unselected_qs_in_x' => '선택된 답변이 없는 질문 ^',
		'unselected_qs_title' => '선택된 답변이 없는 최근 질문',
		'unupvoteda_qs_in_x' => '좋아요 표시를 받은 답변이 없는 질문 in ^',
		'unupvoteda_qs_title' => '좋아요 표시된 답변이 없는 최근 질문',
		'upload_limit' => '너무 많은 업로드 - 몇 시간 후 재시도 해주십시오.',
		'view_q_must_be_approved' => '현재 계정으로 질문 페이지를 보려면 승인을 받아야 합니다.',
		'view_q_must_confirm' => '질문 페이지를 보려면 ^5당신의 이메일 주소를 확인^6해야 합니다.',
		'view_q_must_login' => '질문 페이지를 보려면 ^1로그인^2하거나 ^3가입^4해야 합니다.',
		'viewed_qs_in_x' => '^ 가장 많이 본 질문',
		'viewed_qs_title' => '가장 많이 본 질문',
		'vote_disabled_approve' => '추천하려면 먼저 계정이 승인되어야 합니다.',
		'vote_disabled_down' => '싫어요는 일부 유저만 사용할 수 있습니다',
		'vote_disabled_down_approve' => '싫어요를 하려면 계정을 허가받아야 합니다.',
		'vote_disabled_hidden_a' => '숨긴 답변은 추천할 수 없습니다.',
		'vote_disabled_hidden_q' => '숨긴 질문은 추천할 수 없습니다.',
		'vote_disabled_level' => '일부 유저만 추천할 수 있습니다',
		'vote_disabled_my_a' => '자신의 답변은 추천할 수 없습니다',
		'vote_disabled_my_q' => '자신의 질문은 추천할 수 없습니다',
		'vote_disabled_q_page_only' => '추천하려면 질문을 확인해 주세요.',
		'vote_down_must_confirm' => '싫어요를 하려면 ^5이메일 주소를 확인^6해야 합니다.',
		'vote_down_popup' => '클릭하여 싫어요',
		'vote_limit' => '너무 많은 추천을 받음 - 몇 시간 후 다시 시도해주세요.',
		'vote_must_confirm' => '^5이메일 주소를 확인^6 해야 추천할 수 있습니다.',
		'vote_must_login' => '^1로그인^2 혹은 ^3가입^4 해야 추천할 수 있습니다.',
		'vote_not_allowed' => '추천할 권한이 없습니다.',
		'vote_up_popup' => '클릭하여 좋아요',
		'voted_down_popup' => '싫어요를 하셨습니다. 다시 클릭하여 취소할 수 있습니다.',
		'voted_qs_in_x' => '^가장 많이 추천한 질문',
		'voted_qs_title' => '가장 많이 추천한 질문',
		'voted_up_popup' => '좋아요를 하셨습니다. 다시 클릭하여 취소할 수 있습니다.',
		'written' => 'ko', // blank in English - placeholder for other languages
		'x_ago' => '^ 전에',
		'x_answers' => '^개의 답변',
		'x_comments' => '^개의 댓글',
		'x_days' => '^ 일',
		'x_disliked' => '^명이 싫어함',
		'x_flags' => '^명이 신고함',
		'x_hours' => '^시간',
		'x_liked' => '^명이 좋아함',
		'x_minutes' => '^분',
		'x_months' => '^달',
		'x_points' => '^ 포인트',
		'x_questions' => '^개의 질문',
		'x_seconds' => '^초',
		'x_tags' => '^개의 태그',
		'x_users' => '^명의 유저',
		'x_views' => '^명이 봄',
		'x_votes' => '^추천',
		'x_weeks' => '^주',
		'x_years' => '^년',
	);


/*
	Omit PHP closing tag to help avoid accidental output
*/
